
name: Deploy Database

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id ${{ env.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ env.AWS_SECRET_ACCESS_KEY }}

      - name: Transfer database files
        run: |
          scp -i /path/to/private/ubuntumachine.pem db.sql ec2-user@<3.84.52.76>:~/db.sql

      - name: Connect to EC2 instance and import database
        run: |
          ssh -i /path/to/private/ubuntumachine.pem ec2-user@<3.84.52.76> 'mysql -u <DB_test> -p<Manshu@123> <DB_data> < ~/db.sql'
